#!/bin/csh
#$ -cwd
#$ -V -S /bin/bash
#$ -q gpu.q
#$ -N active_glass

echo "$1_$2_$3"


conda activate hoomd

nohup time  python ../code/activeglass.py $1 $2 $3
# nohup time python snap.py $1 $2
# nohup time python animation.py $1 $2



