#!/bin/csh
#$ -cwd
#$ -V -S /bin/bash
#$ -q gpu.q
#$ -N abp_karman

echo "$1_$2_$3_$4_$5"


conda activate hoomd

nohup time  python ../code/abpkarman.py $1 $2 $3 $4 $5
# nohup time python snap.py $1 $2
# nohup time python animation.py $1 $2



